name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.CML_GITHUB_APP_PEM }}
          app-id: ${{ secrets.CML_GITHUB_APP_ID }}
      - uses: actions/checkout@v3
        token: ${{ steps.get-token.outputs.token }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      - name: cml
        env:
          repo_token: ${{ steps.get-token.outputs.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install -r requirements.txt

          # Pull dataset with DVC
          dvc pull data

          # Reproduce pipeline if any changes detected in dependencies
          dvc repro

          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md master >> report.md
          echo 'Metrics diff done'

          # Add figure to report
          # dvc plots diff --target loss.csv --show-vega master > vega.json
          # vl2png vega.json -s 1.3 > vega.png
          # echo '![](./vega.png)' >> report.md
          cml comment create report.md
